import Navbar from "@/components/Navbar";
import "../../style/globals.css";

export const metadata = {
  title: "Outlook",
  description: "Generated by Abdullah",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
